name: Full-Stack CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install backend dependencies
      run: npm ci
      working-directory: ./server
      
    - name: Run backend tests
      run: npm test
      working-directory: ./server
  
  test-frontend:
    runs-on: ubuntu-latest
    needs: test-backend
    defaults:
      run:
        working-directory: ./client
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install frontend dependencies
      run: npm ci
      working-directory: ./client
      
    - name: Run frontend tests
      run: npm test
      working-directory: ./client
      
    - name: Build React app
      run: npm run build
      working-directory: ./client